name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          # রুট ডিরেক্টরিতে গিয়ে ডিপেন্ডেন্সি ইনস্টল করা হচ্ছে যাতে প্লাগইনগুলো তৈরি হয়
          npm install
          npx cap sync android

      - name: Build with Gradle
        run: |
          cd android/
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Earthquake-App-Final
          path: "android/app/build/outputs/apk/debug/*.apk"
          
